### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by Erioldoesdesign**
Motion graphics files

### CODE REVIEW

**Review by coderberry — APPROVED** [review]
These are amazing!! Great work!

**Comment by RichardLitt** [comment]
Thanks @Erioldoesdesign.

**Comment by RichardLitt** [comment]
Actually - any ideas where to use these? We're not at the moment.

**Comment by Erioldoesdesign** [comment]
> Actually - any ideas where to use these? We're not at the moment.

I used it at the beginning of our youtube mini webinars I now cannot find our youtube channel 😨

**Comment by RichardLitt** [comment]
Here it is! I still have some videos to upload. https://www.youtube.com/channel/UCH7TBTJ12JFaIwfK-0QKClQ

**Pull request merged**
